name: release
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
      types: started
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check and release
        run: |
          CORE_LATEST_VER=$(curl -H "Accept: application/json" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" -s "https://api.github.com/repos/v2ray/v2ray-core/releases/latest" --connect-timeout 10| grep 'tag_name' | cut -d\" -f4)
          CORE_TAG_URL="https://api.github.com/repos/v2ray/v2ray-core/releases/tags/${CORE_LATEST_VER}"
          DIST_TAGS_URL="https://api.github.com/repos/${{ github.repository }}/tags"
          DIST_TAG_FOUND=$(curl -s -L ${DIST_TAGS_URL} | grep "\"name\"\: \"${CORE_LATEST_VER}\"") || true
          if [ -z ${DIST_TAG_FOUND} ]; then
            rm -rf v2update.zip
            wget -O v2update.zip https://github.com/v2fly/v2ray-core/releases/download/${CORE_LATEST_VER}/v2ray-linux-64.zip
            git add .
            git config user.name "dr"
            git config user.email "admin@dr.com"
            git commit -m "Version ${CORE_LATEST_VER}"
            git tag -a "${CORE_LATEST_VER}" -m "Version ${CORE_LATEST_VER}"
            git remote add release "https://github.com/${{ github.repository }}"
            git push -u --follow-tags release master
          fi
